# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: authenticate
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Run Azure CLI Commands'
        run: |
          az account show

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.9
        id: deploy
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./setup/AzureLabEnvironment.bicep
          deploymentMode: Incremental
          region: eastus   
          resourceGroupName: Team2workshop-rg                                                    # Want this driven from an environment variable
          parameters: 'uniqueSuffix=t2 workload=healthapp environment=dev region=eastus publisherEmail=kvr@htm.com publisherName=kvr'  # Can also specify a parameters file location.  Want these driven from environment variables
          failOnStdErr: false